version: '3.6'
services:
  lamp-db:
    container_name: lamp-db
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - lamp-db:/var/lib/mysql/
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lamp
      MYSQL_USER: lamp
      MYSQL_PASSWORD: lamp
    networks:
      - lamp
  lamp-apache_php:
    container_name: lamp-apache_php
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - lamp-db
    volumes:
      - lamp-data:/var/www/html
      - lamp-php:/usr/local/etc/php
      - lamp-conf:/etc/apache2
      - lamp-logs:/var/log/apache2
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.lamp-secure.entrypoints=https
      - traefik.http.routers.lamp-secure.rule=Host(`lamp.domaine.fr`)
      - traefik.http.routers.lamp-secure.tls.certresolver=cert
      - traefik.http.routers.lamp-secure.service=lamp
      - traefik.http.services.lamp.loadbalancer.server.port=80
    networks:
      - lamp
      - web
  lamp-myadmin:
    container_name: lamp-myadmin
    image: phpmyadmin
    restart: unless-stopped
    depends_on:
      - lamp-db
    environment:
      PMA_HOST: lamp-db
      MYSQL_ROOT_PASSWORD: root 
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.lamp-myadmin-secure.entrypoints=https
      - traefik.http.routers.lamp-myadmin-secure.rule=Host(`lamp-myadmin.domaine.fr`)
      - traefik.http.routers.lamp-myadmin-secure.tls.certresolver=cert
      - traefik.http.routers.lamp-myadmin-secure.service=lamp-myadmin
      - traefik.http.services.lamp-myadmin.loadbalancer.server.port=80
    networks:
      - lamp
      - web
volumes:
  lamp-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./lamp-db
  lamp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data
  lamp-php:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./php
  lamp-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./conf
  lamp-logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./logs
networks:
  lamp:
    name: lamp
  web:
    external:
      name: web
