version: '3.6'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'  # for arm64 => yrzr/gitlab-ce-arm64v8:latest
    container_name: gitlab
    restart: unless-stopped
    #hostname: 'gitlab.blabla.fr'
    #environment:
      #GITLAB_OMNIBUS_CONFIG: |
        #external_url 'https://gitlab.blabla.fr'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 449:443
      - 5001:5000
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.gitlab-secure.entrypoints=https
      - traefik.http.routers.gitlab-secure.rule=Host(`gitlab.domaine.fr`)
      - traefik.http.routers.gitlab-secure.tls.certresolver=cert
      - traefik.http.routers.gitlab-secure.service=gitlab
      - traefik.http.services.gitlab.loadbalancer.server.port=80
    networks:
      - web     
networks:
  web:
    external:
      name: web
